framework:
    messenger:
        ##  failure_transport: failed

        transports:
            sync:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            ## failed : '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
            ## failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: [ ]

        routing:
            App\Message\TestMessage: sync


            # Route your messages to the transports
            # 'App\Message\YourMessage': async
